// SPDX-License-Identifier: MIT
// Automatically generated by forge bind-json.

pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {EIP712Types} from 'tests/helpers/mocks/EIP712Types.sol';

interface Vm {
  function parseJsonTypeArray(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function serializeJsonType(
    string calldata typeDescription,
    bytes memory value
  ) external pure returns (string memory json);

  function serializeJsonType(
    string calldata objectKey,
    string calldata valueKey,
    string calldata typeDescription,
    bytes memory value
  ) external returns (string memory json);
}

// solhint-disable quotes
library JsonBindings {
  Vm constant vm = Vm(address(uint160(uint256(keccak256('hevm cheat code')))));

  // prettier-ignore
  string constant schema_SetUserPositionManagers = "SetUserPositionManagers(address onBehalfOf,PositionManagerUpdate[] updates,uint256 nonce,uint256 deadline)PositionManagerUpdate(address positionManager,bool approve)";
  // prettier-ignore
  string constant schema_PositionManagerUpdate = "PositionManagerUpdate(address positionManager,bool approve)";
  // prettier-ignore
  string constant schema_Permit = "Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Supply = "Supply(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Withdraw = "Withdraw(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Borrow = "Borrow(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Repay = "Repay(address spoke,uint256 reserveId,uint256 amount,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SetUsingAsCollateral = "SetUsingAsCollateral(address spoke,uint256 reserveId,bool useAsCollateral,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_UpdateUserRiskPremium = "UpdateUserRiskPremium(address spoke,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_UpdateUserDynamicConfig = "UpdateUserDynamicConfig(address spoke,address onBehalfOf,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_WithdrawPermit = "WithdrawPermit(address spoke,uint256 reserveId,address owner,address spender,uint256 amount,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_BorrowPermit = "BorrowPermit(address spoke,uint256 reserveId,address owner,address spender,uint256 amount,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SetGlobalPermissionPermit = "SetGlobalPermissionPermit(address spoke,address delegator,address delegatee,bool status,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SetCanSetUsingAsCollateralPermissionPermit = "SetCanSetUsingAsCollateralPermissionPermit(address spoke,address delegator,address delegatee,bool status,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SetCanUpdateUserRiskPremiumPermissionPermit = "SetCanUpdateUserRiskPremiumPermissionPermit(address spoke,address delegator,address delegatee,bool status,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_SetCanUpdateUserDynamicConfigPermissionPermit = "SetCanUpdateUserDynamicConfigPermissionPermit(address spoke,address delegator,address delegatee,bool status,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_TokenizedDeposit = "TokenizedDeposit(address depositor,uint256 assets,address receiver,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_TokenizedMint = "TokenizedMint(address depositor,uint256 shares,address receiver,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_TokenizedWithdraw = "TokenizedWithdraw(address owner,uint256 assets,address receiver,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_TokenizedRedeem = "TokenizedRedeem(address owner,uint256 shares,address receiver,uint256 nonce,uint256 deadline)";

  function serialize(
    EIP712Types.SetUserPositionManagers memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SetUserPositionManagers, abi.encode(value));
  }

  function serialize(
    EIP712Types.SetUserPositionManagers memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_SetUserPositionManagers, abi.encode(value));
  }

  function deserializeSetUserPositionManager(
    string memory json
  ) public pure returns (EIP712Types.SetUserPositionManagers memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetUserPositionManagers),
        (EIP712Types.SetUserPositionManagers)
      );
  }

  function deserializeSetUserPositionManager(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManagers memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetUserPositionManagers),
        (EIP712Types.SetUserPositionManagers)
      );
  }

  function deserializeSetUserPositionManagerArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManagers[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetUserPositionManagers),
        (EIP712Types.SetUserPositionManagers[])
      );
  }

  function serialize(EIP712Types.Permit memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Permit, abi.encode(value));
  }

  function serialize(
    EIP712Types.Permit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Permit, abi.encode(value));
  }

  function deserializePermit(string memory json) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Permit), (EIP712Types.Permit[]));
  }

  function serialize(EIP712Types.Supply memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Supply, abi.encode(value));
  }

  function serialize(
    EIP712Types.Supply memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Supply, abi.encode(value));
  }

  function deserializeSupply(string memory json) public pure returns (EIP712Types.Supply memory) {
    return abi.decode(vm.parseJsonType(json, schema_Supply), (EIP712Types.Supply));
  }

  function deserializeSupply(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Supply memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Supply), (EIP712Types.Supply));
  }

  function deserializeSupplyArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Supply[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Supply), (EIP712Types.Supply[]));
  }

  function serialize(EIP712Types.Withdraw memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Withdraw, abi.encode(value));
  }

  function serialize(
    EIP712Types.Withdraw memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Withdraw, abi.encode(value));
  }

  function deserializeWithdraw(
    string memory json
  ) public pure returns (EIP712Types.Withdraw memory) {
    return abi.decode(vm.parseJsonType(json, schema_Withdraw), (EIP712Types.Withdraw));
  }

  function deserializeWithdraw(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Withdraw memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Withdraw), (EIP712Types.Withdraw));
  }

  function deserializeWithdrawArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Withdraw[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Withdraw), (EIP712Types.Withdraw[]));
  }

  function serialize(EIP712Types.Borrow memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Borrow, abi.encode(value));
  }

  function serialize(
    EIP712Types.Borrow memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Borrow, abi.encode(value));
  }

  function deserializeBorrow(string memory json) public pure returns (EIP712Types.Borrow memory) {
    return abi.decode(vm.parseJsonType(json, schema_Borrow), (EIP712Types.Borrow));
  }

  function deserializeBorrow(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Borrow memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Borrow), (EIP712Types.Borrow));
  }

  function deserializeBorrowArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Borrow[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Borrow), (EIP712Types.Borrow[]));
  }

  function serialize(EIP712Types.Repay memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Repay, abi.encode(value));
  }

  function serialize(
    EIP712Types.Repay memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Repay, abi.encode(value));
  }

  function deserializeRepay(string memory json) public pure returns (EIP712Types.Repay memory) {
    return abi.decode(vm.parseJsonType(json, schema_Repay), (EIP712Types.Repay));
  }

  function deserializeRepay(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Repay memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Repay), (EIP712Types.Repay));
  }

  function deserializeRepayArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Repay[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Repay), (EIP712Types.Repay[]));
  }

  function serialize(
    EIP712Types.SetUsingAsCollateral memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SetUsingAsCollateral, abi.encode(value));
  }

  function serialize(
    EIP712Types.SetUsingAsCollateral memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_SetUsingAsCollateral, abi.encode(value));
  }

  function deserializeSetUsingAsCollateral(
    string memory json
  ) public pure returns (EIP712Types.SetUsingAsCollateral memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetUsingAsCollateral),
        (EIP712Types.SetUsingAsCollateral)
      );
  }

  function deserializeSetUsingAsCollateral(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUsingAsCollateral memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetUsingAsCollateral),
        (EIP712Types.SetUsingAsCollateral)
      );
  }

  function deserializeSetUsingAsCollateralArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUsingAsCollateral[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetUsingAsCollateral),
        (EIP712Types.SetUsingAsCollateral[])
      );
  }

  function serialize(
    EIP712Types.UpdateUserRiskPremium memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_UpdateUserRiskPremium, abi.encode(value));
  }

  function serialize(
    EIP712Types.UpdateUserRiskPremium memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_UpdateUserRiskPremium, abi.encode(value));
  }

  function deserializeUpdateUserRiskPremium(
    string memory json
  ) public pure returns (EIP712Types.UpdateUserRiskPremium memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_UpdateUserRiskPremium),
        (EIP712Types.UpdateUserRiskPremium)
      );
  }

  function deserializeUpdateUserRiskPremium(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.UpdateUserRiskPremium memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_UpdateUserRiskPremium),
        (EIP712Types.UpdateUserRiskPremium)
      );
  }

  function deserializeUpdateUserRiskPremiumArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.UpdateUserRiskPremium[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_UpdateUserRiskPremium),
        (EIP712Types.UpdateUserRiskPremium[])
      );
  }

  function serialize(
    EIP712Types.UpdateUserDynamicConfig memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_UpdateUserDynamicConfig, abi.encode(value));
  }

  function serialize(
    EIP712Types.UpdateUserDynamicConfig memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_UpdateUserDynamicConfig, abi.encode(value));
  }

  function deserializeUpdateUserDynamicConfig(
    string memory json
  ) public pure returns (EIP712Types.UpdateUserDynamicConfig memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_UpdateUserDynamicConfig),
        (EIP712Types.UpdateUserDynamicConfig)
      );
  }

  function deserializeUpdateUserDynamicConfig(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.UpdateUserDynamicConfig memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_UpdateUserDynamicConfig),
        (EIP712Types.UpdateUserDynamicConfig)
      );
  }

  function deserializeUpdateUserDynamicConfigArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.UpdateUserDynamicConfig[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_UpdateUserDynamicConfig),
        (EIP712Types.UpdateUserDynamicConfig[])
      );
  }

  function serialize(
    EIP712Types.WithdrawPermit memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_WithdrawPermit, abi.encode(value));
  }

  function serialize(
    EIP712Types.WithdrawPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_WithdrawPermit, abi.encode(value));
  }

  function deserializeWithdrawPermit(
    string memory json
  ) public pure returns (EIP712Types.WithdrawPermit memory) {
    return abi.decode(vm.parseJsonType(json, schema_WithdrawPermit), (EIP712Types.WithdrawPermit));
  }

  function deserializeWithdrawPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.WithdrawPermit memory) {
    return
      abi.decode(vm.parseJsonType(json, path, schema_WithdrawPermit), (EIP712Types.WithdrawPermit));
  }

  function deserializeWithdrawPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.WithdrawPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_WithdrawPermit),
        (EIP712Types.WithdrawPermit[])
      );
  }

  function serialize(EIP712Types.BorrowPermit memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_BorrowPermit, abi.encode(value));
  }

  function serialize(
    EIP712Types.BorrowPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_BorrowPermit, abi.encode(value));
  }

  function deserializeBorrowPermit(
    string memory json
  ) public pure returns (EIP712Types.BorrowPermit memory) {
    return abi.decode(vm.parseJsonType(json, schema_BorrowPermit), (EIP712Types.BorrowPermit));
  }

  function deserializeBorrowPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.BorrowPermit memory) {
    return
      abi.decode(vm.parseJsonType(json, path, schema_BorrowPermit), (EIP712Types.BorrowPermit));
  }

  function deserializeBorrowPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.BorrowPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_BorrowPermit),
        (EIP712Types.BorrowPermit[])
      );
  }

  function serialize(
    EIP712Types.SetGlobalPermissionPermit memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SetGlobalPermissionPermit, abi.encode(value));
  }

  function serialize(
    EIP712Types.SetGlobalPermissionPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(
        objectKey,
        valueKey,
        schema_SetGlobalPermissionPermit,
        abi.encode(value)
      );
  }

  function deserializeSetGlobalPermissionPermit(
    string memory json
  ) public pure returns (EIP712Types.SetGlobalPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetGlobalPermissionPermit),
        (EIP712Types.SetGlobalPermissionPermit)
      );
  }

  function deserializeSetGlobalPermissionPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetGlobalPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetGlobalPermissionPermit),
        (EIP712Types.SetGlobalPermissionPermit)
      );
  }

  function deserializeSetGlobalPermissionPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetGlobalPermissionPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetGlobalPermissionPermit),
        (EIP712Types.SetGlobalPermissionPermit[])
      );
  }

  function serialize(
    EIP712Types.SetCanSetUsingAsCollateralPermissionPermit memory value
  ) internal pure returns (string memory) {
    return
      vm.serializeJsonType(
        schema_SetCanSetUsingAsCollateralPermissionPermit,
        abi.encode(value)
      );
  }

  function serialize(
    EIP712Types.SetCanSetUsingAsCollateralPermissionPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(
        objectKey,
        valueKey,
        schema_SetCanSetUsingAsCollateralPermissionPermit,
        abi.encode(value)
      );
  }

  function deserializeSetCanSetUsingAsCollateralPermissionPermit(
    string memory json
  ) public pure returns (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetCanSetUsingAsCollateralPermissionPermit),
        (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit)
      );
  }

  function deserializeSetCanSetUsingAsCollateralPermissionPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetCanSetUsingAsCollateralPermissionPermit),
        (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit)
      );
  }

  function deserializeSetCanSetUsingAsCollateralPermissionPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetCanSetUsingAsCollateralPermissionPermit),
        (EIP712Types.SetCanSetUsingAsCollateralPermissionPermit[])
      );
  }

  function serialize(
    EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit memory value
  ) internal pure returns (string memory) {
    return
      vm.serializeJsonType(
        schema_SetCanUpdateUserRiskPremiumPermissionPermit,
        abi.encode(value)
      );
  }

  function serialize(
    EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(
        objectKey,
        valueKey,
        schema_SetCanUpdateUserRiskPremiumPermissionPermit,
        abi.encode(value)
      );
  }

  function deserializeSetCanUpdateUserRiskPremiumPermissionPermit(
    string memory json
  ) public pure returns (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetCanUpdateUserRiskPremiumPermissionPermit),
        (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit)
      );
  }

  function deserializeSetCanUpdateUserRiskPremiumPermissionPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetCanUpdateUserRiskPremiumPermissionPermit),
        (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit)
      );
  }

  function deserializeSetCanUpdateUserRiskPremiumPermissionPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetCanUpdateUserRiskPremiumPermissionPermit),
        (EIP712Types.SetCanUpdateUserRiskPremiumPermissionPermit[])
      );
  }

  function serialize(
    EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit memory value
  ) internal pure returns (string memory) {
    return
      vm.serializeJsonType(
        schema_SetCanUpdateUserDynamicConfigPermissionPermit,
        abi.encode(value)
      );
  }

  function serialize(
    EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(
        objectKey,
        valueKey,
        schema_SetCanUpdateUserDynamicConfigPermissionPermit,
        abi.encode(value)
      );
  }

  function deserializeSetCanUpdateUserDynamicConfigPermissionPermit(
    string memory json
  ) public pure returns (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetCanUpdateUserDynamicConfigPermissionPermit),
        (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit)
      );
  }

  function deserializeSetCanUpdateUserDynamicConfigPermissionPermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetCanUpdateUserDynamicConfigPermissionPermit),
        (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit)
      );
  }

  function deserializeSetCanUpdateUserDynamicConfigPermissionPermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetCanUpdateUserDynamicConfigPermissionPermit),
        (EIP712Types.SetCanUpdateUserDynamicConfigPermissionPermit[])
      );
  }

  function serialize(
    EIP712Types.TokenizedDeposit memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_TokenizedDeposit, abi.encode(value));
  }

  function serialize(
    EIP712Types.TokenizedDeposit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_TokenizedDeposit, abi.encode(value));
  }

  function deserializeTokenizedDeposit(
    string memory json
  ) public pure returns (EIP712Types.TokenizedDeposit memory) {
    return
      abi.decode(vm.parseJsonType(json, schema_TokenizedDeposit), (EIP712Types.TokenizedDeposit));
  }

  function deserializeTokenizedDeposit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedDeposit memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_TokenizedDeposit),
        (EIP712Types.TokenizedDeposit)
      );
  }

  function deserializeTokenizedDepositArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedDeposit[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_TokenizedDeposit),
        (EIP712Types.TokenizedDeposit[])
      );
  }

  function serialize(EIP712Types.TokenizedMint memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_TokenizedMint, abi.encode(value));
  }

  function serialize(
    EIP712Types.TokenizedMint memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_TokenizedMint, abi.encode(value));
  }

  function deserializeTokenizedMint(
    string memory json
  ) public pure returns (EIP712Types.TokenizedMint memory) {
    return abi.decode(vm.parseJsonType(json, schema_TokenizedMint), (EIP712Types.TokenizedMint));
  }

  function deserializeTokenizedMint(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedMint memory) {
    return
      abi.decode(vm.parseJsonType(json, path, schema_TokenizedMint), (EIP712Types.TokenizedMint));
  }

  function deserializeTokenizedMintArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedMint[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_TokenizedMint),
        (EIP712Types.TokenizedMint[])
      );
  }

  function serialize(
    EIP712Types.TokenizedWithdraw memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_TokenizedWithdraw, abi.encode(value));
  }

  function serialize(
    EIP712Types.TokenizedWithdraw memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_TokenizedWithdraw, abi.encode(value));
  }

  function deserializeTokenizedWithdraw(
    string memory json
  ) public pure returns (EIP712Types.TokenizedWithdraw memory) {
    return
      abi.decode(vm.parseJsonType(json, schema_TokenizedWithdraw), (EIP712Types.TokenizedWithdraw));
  }

  function deserializeTokenizedWithdraw(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedWithdraw memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_TokenizedWithdraw),
        (EIP712Types.TokenizedWithdraw)
      );
  }

  function deserializeTokenizedWithdrawArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedWithdraw[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_TokenizedWithdraw),
        (EIP712Types.TokenizedWithdraw[])
      );
  }

  function serialize(
    EIP712Types.TokenizedRedeem memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_TokenizedRedeem, abi.encode(value));
  }

  function serialize(
    EIP712Types.TokenizedRedeem memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_TokenizedRedeem, abi.encode(value));
  }

  function deserializeTokenizedRedeem(
    string memory json
  ) public pure returns (EIP712Types.TokenizedRedeem memory) {
    return
      abi.decode(vm.parseJsonType(json, schema_TokenizedRedeem), (EIP712Types.TokenizedRedeem));
  }

  function deserializeTokenizedRedeem(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedRedeem memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_TokenizedRedeem),
        (EIP712Types.TokenizedRedeem)
      );
  }

  function deserializeTokenizedRedeemArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.TokenizedRedeem[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_TokenizedRedeem),
        (EIP712Types.TokenizedRedeem[])
      );
  }
}
